### PR TITLE
testing infrastructure & core.find_* tests

### PR DESCRIPTION
**Pull request by neuromusic**
## TODO
- [ ] clust.py
- [ ] core.py
- [ ] events.py
- [ ] spiketrains.py
- [ ] viz.py

### CODE REVIEW

**Comment by neuromusic** [comment]
@MarvinT @theilmbh should we go ahead and merge this or write more tests first?

**Comment by MarvinT** [comment]
total test coverage: 12%
core.py test coverage: 60%

[Coverage Status](https://coveralls.io/github/gentnerlab/ephys-analysis?branch=testing-merge-justin)

Should we push for a total test coverage of 50%?

**Comment by neuromusic** [comment]
let's prioritize merging this before we start merging the other PRs

## TODO

[ ] clust.py
[ ] core.py
[ ] events.py
[ ] spiketrains.py
[ ] viz.py

**Comment by neuromusic** [comment]
hmm. OK @MarvinT what's the right way to do this now that we have another 30ish commits on master?

merge/rebase this branch against master then keep working on adding test cases?

**Comment by neuromusic** [comment]
also: what's the right approach for testing all of the file reading functions in core.py? 

o.O

should CoreTest.setupClass() create actual kwik/kwx/probe files in the temp dir?

**Comment by MarvinT** [comment]
This is why I have a testing branch based on master, I'll pull changes and make a new pull request because I don't think we can switch targets of a pull request.

Second, I think a good policy to have is to pull these changes in and require that every pull request from here on out increase the coverage. This can usually be done pretty easily by covering the new code by more than our current coverage which is currently at 12%

**Comment by neuromusic** [comment]
OK, I'l let you handle cleaning up the PRs then.

Agreed re increasing test coverage. 12% is a low bar

**Comment by MarvinT** [comment]
Replaced by PR #19

**Pull request closed without merging**
