### PR TITLE
added logic to calculate datetime of trial starts and whether correction trial

### PR DESCRIPTION
**Pull request by neuromusic**
this pull request adds two features:

- each trial gets a datetime that is calculated from the recording metadata (in the info json file) and the time_samples of the trial
- each trial gets a 'correction' column which computes whether the trial was a correction trial (might need to think through the edge cases here better)

### CODE REVIEW

**Comment by neuromusic** [comment]
oh snap. new bar. 23% coverage

@MarvinT will you take a peek at my tests? any tips?

**Comment by MarvinT** [comment]
Very nice! I like them.

Question about `calc_rec_datetime`:
I'm not sure I understand the start_time parameter. 
Maybe we should have a default parameter of 0.
It might also be nice to mention in the documentation that start_time is in seconds.

**Comment by neuromusic** [comment]
these parameters are keys in the 'rec' dictionaries that make_kwd drops into the json file.

that is, each "recording" corresponds to a continuously sampled epoch in Spike2, which starts some time after the beginning of the file. `start_time` is the time in seconds after the start of the file that the recording is sampled from

I'll flesh out the documentation on this

**Comment by neuromusic** [comment]
updated docs. disagree re: default, as the start_time of the recording is rarely 0.0

will merge ASAP

**Pull request merged**
