### PR TITLE
core set of functions for reading from kwik files and common parsing

### PR DESCRIPTION
**Pull request by neuromusic**
### TODO
- [x] split into multiple files
- [x] add full docstrings
- [ ] use decorators to allow filenames or file handlers

### CODE REVIEW

**Comment by neuromusic** [comment]
OK, I cleaned up a lot and it all seems to be working.

Can we go ahead and merge this into master then fork from there to flesh out features & make fixes?

**Comment by MarvinT** [comment]
so for your file_finder decorator, why not do something like:
```
def file_finder(find_file_func):
    @wraps(find_file_func)
    def decorated(block_path,*args,**kwargs):
        ls = glob.glob(os.path.join(block_path, find_file_func(block_path,*args,**kwargs)))
        assert len(ls)==1, ls
        return ls[0]
    return decorated
```
so you can just have 

```
@file_finder
def get_kwik(block_path):
    return '*.kwik'
```
etc. to reduce code duplication slightly more

**Comment by MarvinT** [comment]
Also, for core docstrings, when returning a pandas DataFrame, you should really describe the columns and default values, especially if you say "see core" for documentation elsewhere

**Comment by theilmbh** [comment]
Can we merge this into master sometime soon?

**Comment by neuromusic** [comment]
@MarvinT re `file_finder`, it seems like the utility shouldn't be constrained to assume that the file will like in `block_path`

@theilmbh still need to setup decorator to pass filename or hdf5 handler. will work on that now.

**Comment by neuromusic** [comment]
hmm.

as we originally conceived it w/ zeke, the decorator assumed we were passing either the filename or the file handler (which makes sense) 

```Python
def h5er(block_func):
    def decorated(block,*args,**kwargs):
        if isinstance(block,basestring):
            with h5.File(block,'r') as kf:
                return block_func(kf,*args,**kwargs)
        else:
            return block_func(block,*args,**kwargs)
    return decorated

@h5er 
def get_fs(kwik):
    return kwik['/recordings/0'].attrs['sample_rate']
```

but as written, the core `load_*` functions are taking in the `block_path` then using the `file_finder` to find the appropriate file.

perhaps the better approach is to pull the `find_*` functions out of the `load_*` functions and let the `load_*` functions take the filename or the file handler. users can then use the `find_*` functions to help find the right file. still, this will require users knowing which data is in which file (which is maybe not a bad thing)

thoughts?

**Comment by MarvinT** [comment]
I merged brad's naming conventions in so now we need to finish up the naming conventions. I can do it but I don't want to do it in parallel to someone else's (i.e. @neuromusic ) changes.

- [ ] get_kwx -> find_kwx
- [ ] get_info -> find_info
- [ ] get_fs -> load_fs
- [ ] get_qual -> load_qual
- [ ] get_stim_info -> calc_stim_info
- [ ] get_stim_end
- [ ] get_trials

etc

**Comment by theilmbh** [comment]
Well I committed my changes.  Not sure why it's failing.

**Comment by MarvinT** [comment]
cause the tests aren't pulled in yet right? only testing-merge-justin has
working tests

**Pull request merged**
